<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->a($this->url->get("$plural$"), "Go Back") ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Edit $plural$</h1>
</div>

<?php echo $this->getContent(); ?>

<form action="<?= $this->url->get('$plural$/save') ?>" class="form-horizontal" method="post">
    $captureFields$

    <input
        type="hidden"
        name="$pk$"
        value="<?= htmlspecialchars((string) $singularVar$->$pkGet$, ENT_QUOTES, 'UTF-8') ?>"
    >

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <input type="submit" name="save" value="Save" class="btn btn-primary">
        </div>
    </div>
</form>
